### ISSUE TITLE
 EasyEda no components are valid...

### ISSUE THREAD

**Issue by ear9mrn** [aikopras/RSbus#1]
Hi there. I tried the link you have below to purchase the components to build the through the hole decoder but it appears none of the components listed are valid. I am assuming there are newer/alternates available.

Any chance you could update your EasyEda listing? 

Thanks,

Pete.

**Comment by aikopras** [comment]
Dear Pete

I hope this reply will be received by you. A would appreciate a reply.

The through hole version has “standard components”, that should be available from anywhere.
It can be, however, that the links to Mouser don’t work, but the components are listed here:
https://easyeda.com/aikopras/rs-bus-tht <https://easyeda.com/aikopras/rs-bus-tht>

If you tell me which components you can’t find, I can help.

Bye

Aiko

**Comment by ear9mrn** [comment]
Thanks for your rely. I did as you suggested and went through the list manually and managed to source them all without any problems. I was being lazy and hoping just to place an order via the link.
I have been looking at this solution and one question I have is why did you go down this route rather then use the existing I2C protocol? 

Thanks,

Pete.

**Comment by aikopras** [comment]
Hi Pete

Thanks for your email.

You asked me why I did this route, instead of using I2C.
I guess there are two answers:
1) I have DCC Central Stations from Lenz (LZV100), and I wanted to be compatible with these stations.
2) I2C works over short distances, and can not (out of the box) do busses with length of tens of meters.
485 would have been an alternative (which I’m also using for other stuff), but that is not compatible with the Lenz central stations.

I hope this answers your questions.

Bye

Aiko

**Comment by ear9mrn** [comment]
Aiko,

Thanks again for you response. That make perfect sense. I have been doing a little further research and I am also thinking of trying the Adafruit LTC4311 I2C Extender (to solve the communication distance limitation of I2C as you mentioned) combined with a INA219 I2C Bi-Directional Current Power. I am fully Arduino based system at the moment so not tied to  any particular system...

Thanks,

Pete.
