### ISSUE TITLE
Timer 5 already used

### ISSUE THREAD

**Issue by Digital-MoBa** [aikopras/RSbus#2]
Hi,
with the new use of Timer 5 on the AtMega 2560 processors I can't use anymore the [LocoNet Library](https://github.com/mrrwa/LocoNet) together with the RSbus.
The  [LocoNet Library](https://github.com/mrrwa/LocoNet) use the Timer 5 and the ICP Pin to create a software serial signal.

It it possible to use another timer like **Timer 3** or **Timer 4** on the AtMega 2560 with the RSBus, they have also the 16-bit counter.

regards Philipp

**Comment by aikopras** [comment]
Hi Philipp

Thanks for your question.
I assumed that no-one would use Timer 5, but my assumption proved to be wrong :-)

For the short term you can simply modify sup_isr_sw.cpp. Line 54-57 check the processor, and if it finds a 2560 it uses timer 5. If you change these lines the behaviour changes back to the old behaviour.

I started to use an additional timer since I run into problems with the LCD library, which easily takes 10ms. In my library I needed to call Checkpolling at least every 2ms. By making the logic within CheckPolling timer interrupt driven, it became more reliable.

Since at least someone is using this, I will (happily) change the code. First I will include some #defines in RSbusVariants.h (where I should have put it, but I was too lazy), such that users can decide the timer they like. Second I can change the default timer to 3 or 4. 

If you have other issues, please let me know.

Bye

Aiko

**Comment by aikopras** [comment]
Hi Philipp

I've made a new release (V2.4) where the default Timer is changed from Timer 5 into Timer 3. This should solve the problems in combination with LocoNet. In addition, it is now possible to edit the RSbusVariants.h file, and select Timer 4 or Timer 5 instead.

Let me know if you find any issues.

**Comment by Digital-MoBa** [comment]
Hi,
thank you for the support and the change to support both Interfaces.
Until now I didn't find any issues.
regards Philipp
